export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_DONE = 'SEARCH_DONE';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const SELECT = 'SELECT';
export const VERSION_CHANGE = 'VERSION_CHANGE';

export const INCREMENT_PAGE_INDEX = 'INCREMENT_PAGE_INDEX';
